// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	address "megichains/apps/backendadmin/internal/handler/address"
	auth "megichains/apps/backendadmin/internal/handler/auth"
	evm "megichains/apps/backendadmin/internal/handler/evm"
	fund "megichains/apps/backendadmin/internal/handler/fund"
	open "megichains/apps/backendadmin/internal/handler/open"
	order "megichains/apps/backendadmin/internal/handler/order"
	tron "megichains/apps/backendadmin/internal/handler/tron"
	"megichains/apps/backendadmin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/address/detail",
				Handler: address.AddressDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/address/group/all",
				Handler: address.AddressGroupAllHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/address/group/detail",
				Handler: address.AddressGroupDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/address/group/list",
				Handler: address.AddressGroupListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/address/group/save",
				Handler: address.AddressGroupSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/address/list",
				Handler: address.AddressListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/address/save",
				Handler: address.AddressSaveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/token/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/user/create",
				Handler: auth.UserCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auth/user/info",
				Handler: auth.UserInfoGetHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/evm/log/list",
				Handler: evm.EvmLogListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/fund/list",
				Handler: fund.AddressFundListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/fund/statistics",
				Handler: fund.AddressFundStatisticsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: open.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: open.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/order/detail",
				Handler: order.OrderDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order/list",
				Handler: order.OrderListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/tron/trans/detail",
				Handler: tron.TronTransDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tron/trans/list",
				Handler: tron.TronTransListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
