// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "megichains/apps/backend/internal/handler/auth"
	bsc "megichains/apps/backend/internal/handler/bsc"
	chain "megichains/apps/backend/internal/handler/chain"
	open "megichains/apps/backend/internal/handler/open"
	"megichains/apps/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/token/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/user/create",
				Handler: auth.UserCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auth/user/info",
				Handler: auth.UserInfoGetHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bsc/log/list",
				Handler: bsc.BscLogListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/chain/listen",
				Handler: chain.ChainListenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: open.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/register",
				Handler: open.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
