// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BscTransactionItem struct {
}

type BscTransactionListReq struct {
}

type BscTransactionListResp struct {
	Records []*BscTransactionItem
	Total   int64
	PagesBody
}

type Contacts struct {
	Telegram string `json:"telegram"`
	WhatsApp string `json:"whatsapp"`
	Wechat   string `json:"wechat"`
	Other    string `json:"other"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type Pages struct {
	Current int `form:"current"`
	Size    int `form:"size"`
}

type PagesBody struct {
	Current int `json:"current"`
	Size    int `json:"size"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Success bool `json:"success"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Msg string `json:"msg"`
}

type TronAccountCreateReq struct {
}

type TronAccountCreateResp struct {
}

type TronAccountGetReq struct {
}

type TronAccountGetResp struct {
}

type UserCreateReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserCreateResp struct {
	Success bool `json:"success"`
}

type UserInfoGetReq struct {
}

type UserInfoGetResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}
