// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddressItem struct {
	Id          int64  `json:"id"`
	GroupId     int64  `json:"group_id"`
	Chain       string `json:"chain"`
	Typo        string `json:"typo"`
	Status      string `json:"status"`
	Address     string `json:"address"`
	Address2    string `json:"address2"`
	Description string `json:"description"`
	TimeAts
}

type AddressListReq struct {
	Pages
	StartEnd
	Address string `form:"address,optional"`
	Chain   string `form:"chain,optional"`
	Typo    string `form:typo,optional`
	Status  string `form:"status,optional"`
	GroupId int64  `form:"group_id,optional"`
}

type AddressListResp struct {
	Records []*AddressItem `json:"records"`
	PagesBody
}

type Contacts struct {
	Telegram string `json:"telegram"`
	WhatsApp string `json:"whatsapp"`
	Wechat   string `json:"wechat"`
	Other    string `json:"other"`
}

type EvmLogItem struct {
	Id             int64   `json:"id"`
	Chain          string  `json:"chain"`
	Currency       string  `json:"currency"`
	ChainId        uint64  `json:"chain_id"`
	TxHash         string  `json:"tx_hash"`
	Index          uint    `json:"index"`
	TxIndex        uint    `json:"tx_index"`
	Amount         float64 `json:"amount"`
	Sun            int64   `json:"sun"`
	FromHex        string  `json:"from_hex"`
	ToHex          string  `json:"to_hex"`
	Contract       string  `json:"contract"`
	BlockHash      string  `json:"block_hash"`
	BlockNumber    uint64  `json:"block_number"`
	BlockTimestamp uint64  `json:"block_timestamp"`
	Removed        bool    `json:"removed"`
}

type EvmLogListReq struct {
	Pages
	StartEnd
	Id       int64  `form:"id,optional"`
	Chain    string `form:"chain,optional"`
	Currency string `form:"currency,optional"`
	TxHash   string `form:"tx_hash,optional"`
	FromHex  string `form:"from_hex,optional"`
	ToHex    string `form:"to_hex,optional"`
}

type EvmLogListResp struct {
	Records []*EvmLogItem `json:"records"`
	PagesBody
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type OrderGetReq struct {
	Id int64 `form:"id"`
}

type OrderItem struct {
	Id             int64   `json:"id"`
	MerchOrderId   string  `json:"merch_order_id"`
	LogId          int64   `json:"log_id"`
	TransactionId  string  `json:"transaction_id"`
	Chain          string  `json:"chain"`
	Typo           string  `json:"typo"`
	Status         string  `json:"status"`
	Currency       string  `json:"currency"`
	ReceivedAmount float64 `json:"received_amount"`
	ReceivedSun    int64   `json:"received_sun"`
	FromAddress    string  `json:"from_address"`
	ToAddress      string  `json:"to_address"`
	Description    string  `json:"description"`
	TimeAts
}

type OrderListReq struct {
	Pages
	StartEnd
	Id            int64  `form:"id,optional"`
	MerchOrderId  string `form:"merch_order_id,optional"`
	TransactionId string `form:"transaction_id,optional"`
	Chain         string `form:"chain,optional"`
	Typo          string `form:"typo,optional"`
	Status        string `form:"status,optional"`
	Currency      string `form:"currency,optional"`
	FromAddress   string `form:"from_address,optional"`
	ToAddress     string `form:"to_address,optional"`
}

type OrderListResp struct {
	Records []*OrderItem `json:"records"`
	PagesBody
}

type Pages struct {
	Current int `form:"current"`
	Size    int `form:"size"`
}

type PagesBody struct {
	Current int   `json:"current"`
	Size    int   `json:"size"`
	Total   int64 `json:"total"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Success bool `json:"success"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Msg string `json:"msg"`
}

type StartEnd struct {
	Start int64 `form:"start,optional"`
	End   int64 `form:"end,optional"`
}

type TimeAts struct {
	UpdatedAt uint64 `json:"updated_at"`
	DeletedAt uint64 `json:"deleted_at"`
	CreatedAt uint64 `json:"created_at"`
}

type TronAccountCreateReq struct {
}

type TronAccountCreateResp struct {
}

type TronAccountGetReq struct {
}

type TronAccountGetResp struct {
}

type TronTransItem struct {
	Id             int64   `json:"id"`
	Chain          string  `json:"chain"`
	Currency       string  `json:"currency"`
	TransactionId  string  `json:"transaction_id"`
	Amount         float64 `json:"amount"`
	Sun            int64   `json:"sun"`
	FromBase58     string  `json:"from_base58"`
	ToBase58       string  `json:"to_base58"`
	Contract       string  `json:"contract"`
	BlockTimestamp int64   `json:"block_timestamp"`
	TimeAts
}

type TronTransListReq struct {
	Pages
	StartEnd
	Id            int64  `form:"id,optional"`
	Currency      string `form:"currency,optional"`
	TransactionId string `form:"transaction_id,optional"`
	FromBase58    string `form:"from_base58,optional"`
	ToBase58      string `form:"to_base58,optional"`
}

type TronTransListResp struct {
	Records []*TronTransItem `json:"records"`
	PagesBody
}

type UserCreateReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserCreateResp struct {
	Success bool `json:"success"`
}

type UserInfoGetReq struct {
}

type UserInfoGetResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}
