// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Contacts struct {
	Telegram string `json:"telegram"`
	WhatsApp string `json:"whatsapp"`
	Wechat   string `json:"wechat"`
	Other    string `json:"other"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type OrderItem struct {
	Id             int64   `json:"id"`
	MerchOrderId   string  `json:"merch_order_id"`
	TransactionId  string  `json:"transaction_id"`
	Chain          string  `json:"chain"`
	Typo           string  `json:"typo"`
	Status         string  `json:"status"`
	Currency       string  `json:"currency"`
	ReceivedAmount float64 `json:"received_amount"`
	ReceivedSun    int64   `json:"received_sun"`
	FromAddress    string  `json:"from_address"`
	ToAddress      string  `json:"to_address"`
	Description    string  `json:"description"`
	TimeAts
}

type OrderListReq struct {
	Pages
	StartEnd
	Id            int64  `form:"id,optional"`
	MerchOrderId  string `form:"merch_order_id,optional"`
	TransactionId string `form:"transaction_id,optional"`
	Chain         string `form:"chain,optional"`
	Typo          string `form:"typo,optional"`
	Status        string `form:"status,optional"`
	Currency      string `form:"currency,optional"`
	FromAddress   string `form:"from_address,optional"`
	ToAddress     string `form:"to_address,optional"`
}

type OrderListResp struct {
	Records []*OrderItem `json:"records"`
	PagesBody
}

type Pages struct {
	Current int `form:"current"`
	Size    int `form:"size"`
}

type PagesBody struct {
	Current int   `json:"current"`
	Size    int   `json:"size"`
	Total   int64 `json:"total"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Success bool `json:"success"`
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Msg string `json:"msg"`
}

type StartEnd struct {
	Start int64 `form:"start,optional"`
	End   int64 `form:"end,optional"`
}

type TimeAts struct {
	UpdatedAt uint64 `json:"update_at"`
	DeletedAt uint64 `json:"delete_at"`
	CreatedAt uint64 `json:"created_at"`
}

type TronAccountCreateReq struct {
}

type TronAccountCreateResp struct {
}

type TronAccountGetReq struct {
}

type TronAccountGetResp struct {
}

type UserCreateReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserCreateResp struct {
	Success bool `json:"success"`
}

type UserInfoGetReq struct {
}

type UserInfoGetResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}
